name: Dadsdayout
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://dadsdayout.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: About
   url: /about
 - title: Blog
   url: /index.html
 - title: Contact
   url: /contact
